config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  #define root to location controller with the search method
  root 'location#search'

  #define post request route with root url for submitting location
  post "/", to: 'location#submit', as: "submit"

  #define post request route for creating comments
  post 'location/:id/comments', to: 'comments#create', as: "comment"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :location
  belongs_to :user

end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :comments
  validates :city, :state, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    # generates comment based on specific location
    @location = Location.find(params[:id])
    @comment = @location.comments.create(comment_params)
    # response rendered html partial with local variables passed in
    respond_to do |format|
      format.html { render :partial => "comments/comment",  locals: {comment: @comment} }
    end
  end

  def destroy

    comment_id = params[:comment_id]
    @comment = @user.comments.find(comment_id)
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_path }
      format.json { render json: @comment }
    end
  end

  private
  # allowed comment attributes
  def comment_params
    params.require(:comment).permit(:commenter, :jacket, :top, :pants, :shoes, :body)
  end
end

app/controllers/location_controller.rb
class LocationController < ApplicationController

  def search
    #makes sure the search view is read
  end

  def submit

    #finds or creates a location record in the database using the location parameters
    @location = Location.find_or_create_by(location_params)

    #response can be html or js
    #html renders the comments form partial

    respond_to do |format|
      format.html {render :partial => "comments/form"}
    end
  end

  def destroy

    location_id = params[:user_id]
    @location = @user.location.find(location_id)
    @location.destroy

    respond_to do |format|
      format.html { render :partial => "comments/form" }
      format.json { render json: @location }
    end
  end

  private
  #sets the attributes that are allowed for a comment
  def location_params
    params.require(:location).permit(:city, :state, :location, :location_attribute => [:destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/location_helper.rb
module LocationHelper
def us_states
	{
		:'Alabama' => 'AL',
		:'Alaska' => 'AK',
		:'Arizona' => 'AZ',
		:'Arkansas' => 'AR',
		:'California' => 'CA',
		:'Colorado' => 'CO',
		:'Connecticut' => 'CT',
		:'Delaware' => 'DE',
		:'District of Columbia' => 'DC',
		:'Florida' => 'FL',
		:'Georgia' => 'GA',
		:'Hawaii' => 'HI',
		:'Idaho' => 'ID',
		:'Illinois' => 'IL',
		:'Indiana' => 'IN',
		:'Iowa' => 'IA',
		:'Kansas' => 'KS',
		:'Kentucky' => 'KY',
		:'Louisiana' => 'LA',
		:'Maine' => 'ME',
		:'Maryland' => 'MD',
		:'Massachusetts' => 'MA',
		:'Michigan' => 'MI',
		:'Minnesota' => 'MN',
		:'Mississippi' => 'MS',
		:'Missouri' => 'MO',
		:'Montana' => 'MT',
		:'Nebraska' => 'NE',
		:'Nevada' => 'NV',
		:'New Hampshire' => 'NH',
		:'New Jersey' => 'NJ',
		:'New Mexico' => 'NM',
		:'New York' => 'NY',
		:'North Carolina' => 'NC',
		:'North Dakota' => 'ND',
		:'Ohio' => 'OH',
		:'Oklahoma' => 'OK',
		:'Oregon' => 'OR',
		:'Pennsylvania' => 'PA',
		:'Puerto Rico' => 'PR',
		:'Rhode Island' => 'RI',
		:'South Carolina' => 'SC',
		:'South Dakota' => 'SD',
		:'Tennessee' => 'TN',
		:'Texas' => 'TX',
		:'Utah' => 'UT',
		:'Vermont' => 'VT',
		:'Virginia' => 'VA',
		:'Washington' => 'WA',
		:'West Virginia' => 'WV',
		:'Wisconsin' => 'WI',
		:'Wyoming' => 'WY'
	}
end
end

app/views/comments/_comment.html.erb
<div class="comment-display">
  <p>
    <strong>Name:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Jacket:</strong>
    <%= comment.jacket %>
  </p>

  <p>
    <strong>Top:<strong>
		<%= comment.top %>
	</p>

	<p>
		<strong>Pants:<strong>
		<%= comment.pants %>
	</p>

	<p>
		<strong>Shoes:<strong>
		<%= comment.shoes %>
	</p>

	<p>
		<strong>Picture:<strong>
		<br>
		<img src="http://www.ucarecdn.com/:uuid/-/preview/">
	</p>

	<p>
		<strong>Comment:</strong>
    <%= comment.body %>
  </p>
</div>

app/views/comments/_form.html.erb
<div class="comment-list">
  <% @location.comments.each do |comment| %>

    <%=render partial: "comments/comment", locals: {comment: comment} %>

      <% end %>
</div>

<% if user_signed_in? %>
<div class="comment-form">
  <h1>What are you wearing in this weather?</h1>
  <%= form_for :comment, url: comment_url(id: @location), html: {class: 'submit-comment'} do |f| %>
    <p class="comment-name">
      <%=f.label :name %>
        <br>
        <%=f.text_field :commenter %>
    </p>
    <p class="comment-jacket">
      <%=f.label :jacket %>
        <br>
        <%=f.text_field :jacket %>
    </p>
    <p class="comment-top">
      <%=f.label :top %>
        <br>
        <%=f.text_field :top %>
    </p>
    <p class="comment-pants">
      <%=f.label :pants %>
        <br>
        <%=f.text_field :pants %>
    </p>
    <p class="comment-shoes">
      <%=f.label :shoes %>
        <br>
        <%=f.text_field :shoes %>
    </p>
    <p class="uploadcare-submit">
    <%=f.label :picture %>
      <br>
      
    <%= uploadcare_uploader_field :post, :file %>
      <br>
    </p>
    <p class="comment-body">
      <%=f.label :comment %>
        <br>
        <%=f.text_area :body %>
    </p>
    <p class="submit">
      <%=f.submit 'Submit' %>
    </p>
    <% end %>
</div>
<% else %>
<h2>Login or Sign-up to comment</h2>
 <center><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= include_uploadcare_widget_from_cdn version: "1.5.5", min: true %>
  <%= uploadcare_settings %>

        <title>Forecast Fits</title>
</head>

<body>
  <header>
    <div class="nav">
        <center>
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%=link_to 'Edit profile', edit_user_registration_path, :class=> 'navbar-link' %> |
        <%=link_to "Logout", destroy_user_session_path, method: :delete, :class=> 'navbar-link' %>
          <% else %>
            <%=link_to "Sign up", new_user_registration_path, :class=> 'navbar-link' %> |
              <%=link_to "Login", new_user_session_path, :class=> 'navbar-link' %>
                <% end %>

                  <p class="notice">
                    <%=notice %>
                  </p>
                  <p class="alert">
                    <%=alert %>
                  </p>
  </center>
    </div>
    <img src="/images/small-2137-3489992.png" alt="logo">
      <h1 class="main-title">Forecast Fits</h1>
    <hr>
    <h2>Make sure the forecast fits what you're wearing.</h2>

    <div class="wrapper">
      <div class="location-page">

        <div class="location-form">
          <h1> Where are you? </h1>

          <%=form_for :location, url: submit_url, html: {class: 'search-form'} do |f| %>

            <p class="city-input">
              <%=f.label :City %>
                <%=f.text_field :city %>
            </p>

            <p class="state-input">
              <%=f.label :State %>
                <%=f.select :state, options_for_select(us_states, "CA") %>
            </p>

            <p class="submit">
              <%=f.submit 'Search' %>
            </p>
            <% end %>
        </div>
      </div>
    </div>


  </header>


  <%=yield %>

    <footer>
      <h5> Nic Boutte </h5>

      <hr>

      <a href="https://github.com/Nic510">
        <img class="link-icons" src="/images/github-thumbnail.jpg">
      </a>

      <a href="www.linkedin.com/in/nicboutte/en">
        <img class="link-icons" src="/images/linkedin-thumbnail.jpg">
      </a>
    </footer>

</body>

</html>

app/views/location/search.html.erb
<div class="wrapper">
  <div class="comment-page">

    <div class="api-result hide">

    </div>
  </div>
</div>